
export interface IconData {
    name: string;
    category: string;
    tags: string[];
}

export const galleryIcons: IconData[] = [
    // Food
    { name: 'Kochmütze', category: 'food', tags: ['kochen', 'chef', 'küche', 'gastronomie', 'mütze'] },
    { name: 'Rezept', category: 'food', tags: ['kochen', 'buch', 'anleitung', 'liste', 'zutaten'] },
    { name: 'Burger', category: 'food', tags: ['fastfood', 'essen', 'fleisch', 'amerikanisch', 'brot'] },
    { name: 'Pizza', category: 'food', tags: ['fastfood', 'italienisch', 'essen', 'käse', 'imbiss'] },
    { name: 'Apfel', category: 'food', tags: ['obst', 'gesund', 'frucht', 'vitamin', 'snack'] },
    { name: 'Karotte', category: 'food', tags: ['gemüse', 'gesund', 'orange', 'wurzel', 'vegan'] },
    { name: 'Brot', category: 'food', tags: ['backen', 'frühstück', 'teig', 'weizen', 'bäcker'] },
    { name: 'Kaffee', category: 'food', tags: ['getränk', 'koffein', 'frühstück', 'tasse', 'heiss'] },
    { name: 'Tee', category: 'food', tags: ['getränk', 'heiss', 'kräuter', 'tasse', 'entspannung'] },
    { name: 'Eis', category: 'food', tags: ['dessert', 'sommer', 'kalt', 'süss', 'kugel'] },
    { name: 'Kuchen', category: 'food', tags: ['dessert', 'gebäck', 'süss', 'feier', 'geburtstag'] },
    { name: 'Fischgericht', category: 'food', tags: ['meer', 'essen', 'protein', 'gesund', 'speise'] },
    { name: 'Fleisch', category: 'food', tags: ['steak', 'protein', 'grill', 'essen', 'rind'] },
    { name: 'Salat', category: 'food', tags: ['gesund', 'gemüse', 'vegan', 'diät', 'grün'] },
    { name: 'Suppe', category: 'food', tags: ['heiss', 'essen', 'schüssel', 'löffel', 'mahlzeit'] },
    { name: 'Getränk', category: 'food', tags: ['soda', 'glas', 'erfrischung', 'wasser', 'limonade'] },
    { name: 'Besteck', category: 'food', tags: ['gabel', 'messer', 'löffel', 'essen', 'tisch'] },
    { name: 'Teller', category: 'food', tags: ['geschirr', 'essen', 'küche', 'keramik', 'flach'] },
    { name: 'Grill', category: 'food', tags: ['bbq', 'sommer', 'fleisch', 'feuer', 'garten'] },
    { name: 'Sushi', category: 'food', tags: ['japanisch', 'fisch', 'reis', 'rolle', 'asiatisch'] },

    // Health
    { name: 'Hantel', category: 'health', tags: ['sport', 'fitness', 'kraft', 'training', 'studio'] },
    { name: 'Herz (Organ)', category: 'health', tags: ['organ', 'leben', 'puls', 'medizin', 'körper'] },
    { name: 'Arzt', category: 'health', tags: ['doktor', 'krankenhaus', 'medizin', 'beruf', 'hilfe'] },
    { name: 'Pille', category: 'health', tags: ['medikament', 'kapsel', 'apotheke', 'medizin', 'tablette'] },
    { name: 'Spritze', category: 'health', tags: ['medizin', 'impfung', 'nadel', 'injektion', 'krankenhaus'] },
    { name: 'Krankenwagen', category: 'health', tags: ['notfall', 'auto', 'rettung', 'sirene', 'schnell'] },
    { name: 'Pflaster', category: 'health', tags: ['wunde', 'verletzung', 'hilfe', 'verband', 'medizin'] },
    { name: 'Zahn', category: 'health', tags: ['zahnarzt', 'mund', 'pflege', 'weiss', 'hygiene'] },
    { name: 'Augen', category: 'health', tags: ['sehen', 'blick', 'organ', 'optiker', 'sicht'] },
    { name: 'Gehirn', category: 'health', tags: ['denken', 'organ', 'kopf', 'intelligenz', 'nerven'] },
    { name: 'Lunge', category: 'health', tags: ['atem', 'organ', 'luft', 'medizin', 'körper'] },
    { name: 'Virus', category: 'health', tags: ['krankheit', 'bakterie', 'mikro', 'infektion', 'medizin'] },
    { name: 'Medizinische Maske', category: 'health', tags: ['schutz', 'hygiene', 'gesicht', 'medizin', 'covid'] },
    { name: 'Thermometer', category: 'health', tags: ['temperatur', 'fieber', 'messung', 'krank', 'grad'] },
    { name: 'Rollstuhl', category: 'health', tags: ['behinderung', 'hilfe', 'mobilität', 'krankenhaus', 'sitz'] },
    { name: 'Yoga', category: 'health', tags: ['entspannung', 'sport', 'meditation', 'pose', 'fitness'] },
    { name: 'Blutdruck', category: 'health', tags: ['herz', 'medizin', 'messung', 'gesundheit', 'arzt'] },
    { name: 'Erste Hilfe', category: 'health', tags: ['notfall', 'koffer', 'kreuz', 'rettung', 'medizin'] },
    { name: 'Vitamine', category: 'health', tags: ['gesund', 'nahrung', 'ergänzung', 'medizin', 'kapseln'] },

    // Travel (nur reisebezogene Objekte, keine Fahrzeuge)
    { name: 'Landkarte', category: 'travel', tags: ['orientierung', 'weg', 'papier', 'welt', 'planung'] },
    { name: 'Koffer', category: 'travel', tags: ['gepäck', 'urlaub', 'packen', 'reise', 'tasche'] },
    { name: 'Reisepass', category: 'travel', tags: ['identität', 'grenze', 'dokument', 'reise', 'buch'] },
    { name: 'Reiseticket', category: 'travel', tags: ['eintritt', 'karte', 'papier', 'reise', 'buchung'] },
    { name: 'Kompass', category: 'travel', tags: ['richtung', 'nord', 'orientierung', 'navigation', 'gerät'] },
    { name: 'Hotel', category: 'travel', tags: ['übernachtung', 'bett', 'urlaub', 'gebäude', 'schlafen'] },
    { name: 'Strand', category: 'travel', tags: ['meer', 'sonne', 'sand', 'urlaub', 'entspannung'] },
    { name: 'Berg', category: 'travel', tags: ['natur', 'wandern', 'gipfel', 'aussicht', 'landschaft'] },
    { name: 'Zelt', category: 'travel', tags: ['camping', 'outdoor', 'natur', 'schlafen', 'abenteuer'] },
    { name: 'Wanderrucksack', category: 'travel', tags: ['wandern', 'trekking', 'gepäck', 'outdoor', 'rücken'] },
    { name: 'Wegweiser', category: 'travel', tags: ['richtung', 'schild', 'orientierung', 'strasse', 'entscheidung'] },
    { name: 'Insel', category: 'travel', tags: ['meer', 'palme', 'urlaub', 'land', 'wasser'] },
    { name: 'Sehenswürdigkeit', category: 'travel', tags: ['denkmal', 'statue', 'geschichte', 'tourismus', 'stadt'] },
    { name: 'Brücke', category: 'travel', tags: ['verbindung', 'architektur', 'fluss', 'strasse', 'weg'] },

    // Finance
    { name: 'Geldbeutel', category: 'finance', tags: ['geld', 'bezahlen', 'leder', 'tasche', 'vermögen'] },
    { name: 'Münze', category: 'finance', tags: ['geld', 'metall', 'bezahlen', 'kleingeld', 'rund'] },
    { name: 'Geldschein', category: 'finance', tags: ['geld', 'papier', 'bezahlen', 'banknote', 'cash'] },
    { name: 'Kreditkarte', category: 'finance', tags: ['bezahlen', 'plastik', 'bank', 'geld', 'kaufen'] },
    { name: 'Bank', category: 'finance', tags: ['gebäude', 'geld', 'konto', 'finanzen', 'sparen'] },
    { name: 'Sparschwein', category: 'finance', tags: ['sparen', 'geld', 'tier', 'keramik', 'zukunft'] },
    { name: 'Diagramm', category: 'finance', tags: ['statistik', 'wachstum', 'analyse', 'daten', 'business'] },
    { name: 'Aktie', category: 'finance', tags: ['börse', 'investition', 'kurs', 'papier', 'markt'] },
    { name: 'Taschenrechner', category: 'finance', tags: ['mathe', 'zahlen', 'gerät', 'büro', 'rechnen'] },
    { name: 'Tresor', category: 'finance', tags: ['sicherheit', 'geld', 'stahl', 'schloss', 'bank'] },
    { name: 'Währungstausch', category: 'finance', tags: ['geld', 'austausch', 'international', 'wechseln', 'markt'] },
    { name: 'Dollar', category: 'finance', tags: ['geld', 'usa', 'währung', 'symbol', 'business'] },
    { name: 'Euro', category: 'finance', tags: ['geld', 'europa', 'währung', 'symbol', 'business'] },
    { name: 'Bitcoin', category: 'finance', tags: ['krypto', 'digital', 'geld', 'blockchain', 'münze'] },
    { name: 'Rechnung', category: 'finance', tags: ['papier', 'bezahlen', 'kosten', 'steuer', 'liste'] },
    { name: 'Steuer', category: 'finance', tags: ['finanzamt', 'geld', 'gesetz', 'papier', 'kosten'] },
    { name: 'Gewinn', category: 'finance', tags: ['wachstum', 'geld', 'pfeil', 'erfolg', 'business'] },
    { name: 'Verlust', category: 'finance', tags: ['abstieg', 'geld', 'pfeil', 'risiko', 'business'] },
    { name: 'Investition', category: 'finance', tags: ['wachstum', 'geld', 'baum', 'zukunft', 'plan'] },
    { name: 'Börse', category: 'finance', tags: ['markt', 'handel', 'gebäude', 'aktien', 'finanzen'] },

    // Utility
    { name: 'Wolke', category: 'utility', tags: ['wetter', 'himmel', 'daten', 'speicher', 'internet'] },
    { name: 'Schraubenschlüssel', category: 'utility', tags: ['werkzeug', 'reparatur', 'mechanik', 'drehen', 'metall'] },
    { name: 'Hammer', category: 'utility', tags: ['werkzeug', 'bauen', 'nagel', 'schlag', 'handwerk'] },
    { name: 'Zange', category: 'utility', tags: ['werkzeug', 'greifen', 'metall', 'handwerk', 'reparatur'] },
    { name: 'Säge', category: 'utility', tags: ['werkzeug', 'holz', 'schneiden', 'zähne', 'handwerk'] },
    { name: 'Bohrmaschine', category: 'utility', tags: ['maschine', 'loch', 'bauen', 'elektrisch', 'handwerk'] },
    { name: 'Leiter', category: 'utility', tags: ['höhe', 'steigen', 'holz', 'werkzeug', 'hilfe'] },
    { name: 'Pinsel', category: 'utility', tags: ['malen', 'farbe', 'kunst', 'streichen', 'werkzeug'] },
    { name: 'Eimer', category: 'utility', tags: ['wasser', 'tragen', 'plastik', 'putzen', 'gefäss'] },
    { name: 'Besen', category: 'utility', tags: ['putzen', 'sauber', 'haushalt', 'reinigung', 'holz'] },
    { name: 'Schaufel', category: 'utility', tags: ['graben', 'garten', 'erde', 'werkzeug', 'bauen'] },
    { name: 'Axt', category: 'utility', tags: ['holz', 'hacken', 'wald', 'werkzeug', 'scharf'] },
    { name: 'Zollstock', category: 'utility', tags: ['messen', 'länge', 'werkzeug', 'genau', 'bauen'] },
    { name: 'Klebeband', category: 'utility', tags: ['befestigen', 'rolle', 'reparatur', 'büro', 'kleben'] },
    { name: 'Nagel', category: 'utility', tags: ['metall', 'spitz', 'hammer', 'befestigen', 'bauen'] },
    { name: 'Schraube', category: 'utility', tags: ['metall', 'gewinde', 'drehen', 'befestigen', 'werkzeug'] },
    { name: 'Stecker', category: 'utility', tags: ['strom', 'kabel', 'energie', 'elektrisch', 'dose'] },
    { name: 'Kabel', category: 'utility', tags: ['verbindung', 'strom', 'lang', 'elektrisch', 'technik'] },
    { name: 'Batterie', category: 'utility', tags: ['energie', 'strom', 'aufladen', 'power', 'klein'] },
    { name: 'Glühbirne', category: 'utility', tags: ['licht', 'idee', 'strom', 'glas', 'hell'] },

    // Shopping
    { name: 'Einkaufswagen', category: 'shopping', tags: ['wagen', 'supermarkt', 'kaufen', 'metall', 'rollen'] },
    { name: 'Einkaufstasche', category: 'shopping', tags: ['tragen', 'einkauf', 'stoff', 'papier', 'plastik'] },
    { name: 'Einkaufskorb', category: 'shopping', tags: ['tragen', 'supermarkt', 'flechten', 'griff', 'kaufen'] },
    { name: 'Barcode', category: 'shopping', tags: ['scan', 'preis', 'produkt', 'kasse', 'code'] },
    { name: 'Preisschild', category: 'shopping', tags: ['label', 'kosten', 'info', 'produkt', 'verkauf'] },
    { name: 'Rabatt', category: 'shopping', tags: ['prozent', 'sparen', 'angebot', 'sale', 'günstig'] },
    { name: 'Geschenk', category: 'shopping', tags: ['überraschung', 'paket', 'feier', 'schleife', 'geben'] },
    { name: 'Laden', category: 'shopping', tags: ['geschäft', 'gebäude', 'verkauf', 'markt', 'einkaufen'] },
    { name: 'Kasse', category: 'shopping', tags: ['bezahlen', 'geld', 'laden', 'maschine', 'rechnung'] },
    { name: 'Quittung', category: 'shopping', tags: ['papier', 'nachweis', 'kauf', 'liste', 'steuer'] },
    { name: 'Kunde', category: 'shopping', tags: ['person', 'kaufen', 'service', 'markt', 'besucher'] },
    { name: 'Verkäufer', category: 'shopping', tags: ['person', 'arbeit', 'service', 'laden', 'beruf'] },
    { name: 'Lieferung', category: 'shopping', tags: ['lkw', 'paket', 'transport', 'schnell', 'service'] },
    { name: 'Versandpaket', category: 'shopping', tags: ['karton', 'post', 'inhalt', 'lieferung', 'box'] },
    { name: 'Versandkarton', category: 'shopping', tags: ['box', 'verpackung', 'lager', 'pappe', 'transport'] },
    { name: 'Marke', category: 'shopping', tags: ['logo', 'qualität', 'produkt', 'symbol', 'firma'] },
    { name: 'Sale', category: 'shopping', tags: ['angebot', 'rabatt', 'kaufen', 'günstig', 'aktion'] },
    { name: 'Gutschein', category: 'shopping', tags: ['geschenk', 'wert', 'ticket', 'bezahlen', 'karte'] },
    { name: 'Bestellung', category: 'shopping', tags: ['online', 'liste', 'kauf', 'prozess', 'paket'] },
    { name: 'Rückgabe', category: 'shopping', tags: ['pfeil', 'zurück', 'umtausch', 'service', 'paket'] },

    // Education
    { name: 'Buch', category: 'education', tags: ['lesen', 'lernen', 'schule', 'wissen', 'papier'] },
    { name: 'Stift', category: 'education', tags: ['schreiben', 'büro', 'schule', 'tinte', 'werkzeug'] },
    { name: 'Heft', category: 'education', tags: ['schreiben', 'notiz', 'papier', 'schule', 'buch'] },
    { name: 'Schultafel', category: 'education', tags: ['schule', 'lehrer', 'kreide', 'grün', 'unterricht'] },
    { name: 'Lehrer', category: 'education', tags: ['beruf', 'schule', 'unterricht', 'person', 'erklärung'] },
    { name: 'Schüler', category: 'education', tags: ['lernen', 'schule', 'kind', 'klasse', 'person'] },
    { name: 'Schule', category: 'education', tags: ['gebäude', 'lernen', 'klasse', 'bildung', 'haus'] },
    { name: 'Universität', category: 'education', tags: ['studium', 'gebäude', 'abschluss', 'bildung', 'campus'] },
    { name: 'Diplom', category: 'education', tags: ['abschluss', 'zertifikat', 'rolle', 'erfolg', 'papier'] },
    { name: 'Doktorhut', category: 'education', tags: ['abschluss', 'uni', 'feier', 'kleidung', 'schwarz'] },
    { name: 'Schulrucksack', category: 'education', tags: ['schule', 'tragen', 'tasche', 'bücher', 'schüler'] },
    { name: 'Mikroskop', category: 'education', tags: ['wissenschaft', 'labor', 'sehen', 'biologie', 'klein'] },
    { name: 'Reagenzglas', category: 'education', tags: ['chemie', 'labor', 'glas', 'experiment', 'flüssigkeit'] },
    { name: 'Atom', category: 'education', tags: ['physik', 'wissenschaft', 'klein', 'energie', 'kern'] },
    { name: 'Mathematische Formel', category: 'education', tags: ['mathe', 'tafel', 'rechnen', 'wissenschaft', 'gleichung'] },
    { name: 'Zahlen', category: 'education', tags: ['mathe', '123', 'rechnen', 'zählen', 'schule'] },
    { name: 'Buchstaben', category: 'education', tags: ['abc', 'sprache', 'lesen', 'schule', 'schreiben'] },
    { name: 'Bibliothek', category: 'education', tags: ['bücher', 'lesen', 'gebäude', 'stille', 'wissen'] },
    { name: 'Globus', category: 'education', tags: ['erde', 'geografie', 'welt', 'schule', 'karte'] },

    // Entertainment
    { name: 'Musiknoten', category: 'entertainment', tags: ['musik', 'lied', 'klang', 'symbol', 'kunst'] },
    { name: 'Fotokamera', category: 'entertainment', tags: ['foto', 'bild', 'aufnahme', 'linse', 'hobby'] },
    { name: 'Film', category: 'entertainment', tags: ['kino', 'movie', 'streifen', 'video', 'aufnahme'] },
    { name: 'Eventticket', category: 'entertainment', tags: ['eintritt', 'kino', 'konzert', 'karte', 'event'] },
    { name: 'Popcorn', category: 'entertainment', tags: ['kino', 'essen', 'snack', 'mais', 'film'] },
    { name: 'Mikrofon', category: 'entertainment', tags: ['singen', 'aufnahme', 'stimme', 'audio', 'bühne'] },
    { name: 'Gitarre', category: 'entertainment', tags: ['musik', 'instrument', 'saiten', 'rock', 'band'] },
    { name: 'Klavier', category: 'entertainment', tags: ['musik', 'instrument', 'tasten', 'klassik', 'schwarz'] },
    { name: 'Schlagzeug', category: 'entertainment', tags: ['musik', 'instrument', 'trommel', 'beat', 'rhythmus'] },
    { name: 'Game Controller', category: 'entertainment', tags: ['spiel', 'game', 'konsole', 'spass', 'tasten'] },
    { name: 'Fernseher', category: 'entertainment', tags: ['tv', 'bildschirm', 'serie', 'film', 'wohnzimmer'] },
    { name: 'Radio', category: 'entertainment', tags: ['musik', 'nachrichten', 'audio', 'sender', 'vintage'] },
    { name: 'Kopfhörer', category: 'entertainment', tags: ['musik', 'hören', 'audio', 'ohren', 'sound'] },
    { name: 'Lautsprecher', category: 'entertainment', tags: ['musik', 'sound', 'box', 'audio', 'laut'] },
    { name: 'Bühne', category: 'entertainment', tags: ['theater', 'show', 'licht', 'performance', 'platz'] },
    { name: 'Theatermaske', category: 'entertainment', tags: ['theater', 'verkleidung', 'drama', 'gesicht', 'kunst'] },
    { name: 'Zauberstab', category: 'entertainment', tags: ['magie', 'show', 'trick', 'stern', 'wunder'] },
    { name: 'Spielwürfel', category: 'entertainment', tags: ['spiel', 'glück', 'brettspiel', 'zufall', 'würfel'] },
    { name: 'Schachfigur', category: 'entertainment', tags: ['schach', 'spiel', 'strategie', 'brett', 'denken'] },
    { name: 'Spielkarte', category: 'entertainment', tags: ['spiel', 'poker', 'ass', 'glück', 'kasino'] },

    // Productivity
    { name: 'Aktenordner', category: 'productivity', tags: ['büro', 'papier', 'sortieren', 'archiv', 'dokument'] },
    { name: 'Kalender', category: 'productivity', tags: ['datum', 'zeit', 'plan', 'termin', 'monat'] },
    { name: 'Uhr', category: 'productivity', tags: ['zeit', 'stunde', 'wecker', 'früh', 'messen'] },
    { name: 'Checkliste', category: 'productivity', tags: ['aufgaben', 'erledigen', 'plan', 'haken', 'liste'] },
    { name: 'Notizzettel', category: 'productivity', tags: ['schreiben', 'zettel', 'erinnerung', 'papier', 'idee'] },
    { name: 'Papier', category: 'productivity', tags: ['blatt', 'schreiben', 'dokument', 'leer', 'weiss'] },
    { name: 'Tacker', category: 'productivity', tags: ['büro', 'befestigen', 'klammer', 'werkzeug', 'papier'] },
    { name: 'Schere', category: 'productivity', tags: ['schneiden', 'werkzeug', 'basteln', 'büro', 'scharf'] },
    { name: 'Büroklammer', category: 'productivity', tags: ['halten', 'metall', 'papier', 'büro', 'klein'] },
    { name: 'Brief', category: 'productivity', tags: ['post', 'nachricht', 'umschlag', 'senden', 'mail'] },
    { name: 'E-Mail', category: 'productivity', tags: ['digital', 'post', 'nachricht', 'at-zeichen', 'internet'] },
    { name: 'Telefon', category: 'productivity', tags: ['anruf', 'sprechen', 'kommunikation', 'gerät', 'kontakt'] },
    { name: 'Meeting', category: 'productivity', tags: ['treffen', 'arbeit', 'team', 'besprechung', 'tisch'] },
    { name: 'Zielscheibe', category: 'productivity', tags: ['erfolg', 'pfeil', 'scheibe', 'treffen', 'fokus'] },
    { name: 'Erfolgspokal', category: 'productivity', tags: ['pokal', 'gewinn', 'sieger', 'ziel', 'best'] },
    { name: 'Projektplan', category: 'productivity', tags: ['strategie', 'karte', 'idee', 'schritt', 'weg'] },
    { name: 'Strategie', category: 'productivity', tags: ['schach', 'plan', 'ziel', 'denken', 'zukunft'] },
    { name: 'Fokus', category: 'productivity', tags: ['ziel', 'lupe', 'konzentration', 'wichtig', 'sehen'] },

    // Social
    { name: 'Smartphone', category: 'social', tags: ['handy', 'anruf', 'mobil', 'app', 'kommunikation'] },
    { name: 'Chat', category: 'social', tags: ['nachricht', 'sprechblase', 'text', 'dialog', 'reden'] },
    { name: 'Benutzerprofil', category: 'social', tags: ['person', 'profil', 'account', 'login', 'avatar'] },
    { name: 'Benutzergruppe', category: 'social', tags: ['team', 'menschen', 'freunde', 'gemeinschaft', 'zusammen'] },
    { name: 'Herz (Like)', category: 'social', tags: ['like', 'liebe', 'favorit', 'social-media', 'rot'] },
    { name: 'Daumen hoch', category: 'social', tags: ['like', 'gut', 'bestätigung', 'ok', 'positiv'] },
    { name: 'Teilen', category: 'social', tags: ['share', 'weiterleiten', 'pfeil', 'netzwerk', 'verbreiten'] },
    { name: 'Kommentar', category: 'social', tags: ['meinung', 'sprechblase', 'text', 'feedback', 'antwort'] },
    { name: 'Freund hinzufügen', category: 'social', tags: ['plus', 'neu', 'freund', 'kontakt', 'verbinden'] },
    { name: 'Blockieren', category: 'social', tags: ['stopp', 'verbot', 'nein', 'schutz', 'sperre'] },
    { name: 'Benachrichtigung', category: 'social', tags: ['glocke', 'alarm', 'neu', 'info', 'klingel'] },
    { name: 'Soziales Netzwerk', category: 'social', tags: ['verbindung', 'knoten', 'community', 'sozial', 'struktur'] },
    { name: 'Verbindung', category: 'social', tags: ['link', 'kette', 'zusammen', 'kontakt', 'stark'] },
    { name: 'Freunde', category: 'social', tags: ['spass', 'zusammen', 'menschen', 'beziehung', 'lachen'] },
    { name: 'Familie', category: 'social', tags: ['eltern', 'kinder', 'zuhause', 'liebe', 'zusammen'] },
    { name: 'Geburtstagsfeier', category: 'social', tags: ['geburtstag', 'feier', 'kuchen', 'jahr', 'kerze'] },
    { name: 'Party', category: 'social', tags: ['feier', 'ballon', 'musik', 'spass', 'event'] },
    { name: 'Einladung', category: 'social', tags: ['brief', 'karte', 'termin', 'gäste', 'willkommen'] },
    { name: 'Geschenkbox', category: 'social', tags: ['geschenk', 'geben', 'box', 'schleife', 'überraschung'] },

    // Technology
    { name: 'Desktop Computer', category: 'technology', tags: ['pc', 'desktop', 'screen', 'arbeit', 'digital'] },
    { name: 'Laptop', category: 'technology', tags: ['mobil', 'computer', 'arbeit', 'klappbar', 'tech'] },
    { name: 'Tablet', category: 'technology', tags: ['touch', 'mobil', 'screen', 'flach', 'pad'] },
    { name: 'Server', category: 'technology', tags: ['daten', 'cloud', 'rack', 'speicher', 'netzwerk'] },
    { name: 'Datenbank', category: 'technology', tags: ['sql', 'speicher', 'daten', 'silo', 'struktur'] },
    { name: 'Prozessor', category: 'technology', tags: ['cpu', 'chip', 'silizium', 'platine', 'hirn'] },
    { name: 'Programmcode', category: 'technology', tags: ['programmieren', 'klammern', 'script', 'entwickler', 'html'] },
    { name: 'Roboter', category: 'technology', tags: ['ki', 'automat', 'zukunft', 'maschine', 'android'] },
    { name: 'Computernetzwerk', category: 'technology', tags: ['internet', 'verbindung', 'nodes', 'web', 'system'] },
    { name: 'WLAN', category: 'technology', tags: ['wifi', 'funk', 'internet', 'signal', 'kabellos'] },
    { name: 'Bluetooth', category: 'technology', tags: ['funk', 'verbindung', 'blau', 'zahn', 'kabellos'] },
    { name: 'USB-Stick', category: 'technology', tags: ['usb', 'stick', 'speicher', 'stecker', 'daten'] },
    { name: 'Festplatte', category: 'technology', tags: ['hdd', 'ssd', 'speicher', 'daten', 'backup'] },
    { name: 'Computermaus', category: 'technology', tags: ['maus', 'klick', 'cursor', 'steuerung', 'eingabe'] },
    { name: 'Tastatur', category: 'technology', tags: ['tippen', 'eingabe', 'tasten', 'text', 'schreiben'] },
    { name: 'Monitor', category: 'technology', tags: ['bildschirm', 'display', 'pixel', 'hd', 'sehen'] },
    { name: 'Drucker', category: 'technology', tags: ['papier', 'ausgabe', 'tinte', 'kopie', 'gerät'] },
    { name: 'Scanner', category: 'technology', tags: ['digitalisieren', 'kopie', 'licht', 'bild', 'dokument'] },
    { name: 'Webcam', category: 'technology', tags: ['webcam', 'video', 'aufnahme', 'linse', 'konferenz'] },
    { name: 'Drohne', category: 'technology', tags: ['flug', 'kamera', 'fernsteuerung', 'roboter', 'luft'] },

    // Home
    { name: 'Blume', category: 'home', tags: ['pflanze', 'natur', 'deko', 'garten', 'duft'] },
    { name: 'Haus', category: 'home', tags: ['gebäude', 'wohnen', 'dach', 'familie', 'heim'] },
    { name: 'Schlüssel', category: 'home', tags: ['tür', 'öffnen', 'sicherheit', 'metall', 'zugang'] },
    { name: 'Tür', category: 'home', tags: ['eingang', 'ausgang', 'holz', 'offen', 'raum'] },
    { name: 'Fenster', category: 'home', tags: ['glas', 'blick', 'licht', 'lüften', 'rahmen'] },
    { name: 'Bett', category: 'home', tags: ['schlafen', 'möbel', 'ausruhen', 'nacht', 'kissen'] },
    { name: 'Sofa', category: 'home', tags: ['couch', 'sitzen', 'wohnzimmer', 'bequem', 'möbel'] },
    { name: 'Stuhl', category: 'home', tags: ['sitzen', 'möbel', 'tisch', 'holz', 'lehne'] },
    { name: 'Tisch', category: 'home', tags: ['möbel', 'essen', 'arbeit', 'platte', 'beine'] },
    { name: 'Lampe', category: 'home', tags: ['licht', 'leuchten', 'strom', 'birne', 'hell'] },
    { name: 'Teppich', category: 'home', tags: ['boden', 'stoff', 'weich', 'deko', 'wohnzimmer'] },
    { name: 'Wandbild', category: 'home', tags: ['kunst', 'rahmen', 'wand', 'foto', 'deko'] },
    { name: 'Zimmerpflanze', category: 'home', tags: ['grün', 'topf', 'natur', 'wachsen', 'deko'] },
    { name: 'Garten', category: 'home', tags: ['draussen', 'natur', 'blumen', 'rasen', 'hobby'] },
    { name: 'Küche', category: 'home', tags: ['kochen', 'essen', 'raum', 'herd', 'spüle'] },
    { name: 'Badezimmer', category: 'home', tags: ['bad', 'dusche', 'waschen', 'raum', 'hygiene'] },
    { name: 'Dusche', category: 'home', tags: ['wasser', 'waschen', 'bad', 'sauber', 'nass'] },
    { name: 'Toilette', category: 'home', tags: ['wc', 'bad', 'keramik', 'hygiene', 'spülung'] },
    { name: 'Waschmaschine', category: 'home', tags: ['wäsche', 'sauber', 'kleidung', 'trommel', 'gerät'] },
    { name: 'Staubsauger', category: 'home', tags: ['putzen', 'staub', 'boden', 'gerät', 'sauber'] },

    // Pets
    { name: 'Hund', category: 'pets', tags: ['tier', 'bellen', 'freund', 'haustier', 'treu'] },
    { name: 'Katze', category: 'pets', tags: ['tier', 'miauen', 'schnurren', 'fell', 'haustier'] },
    { name: 'Vogel', category: 'pets', tags: ['tier', 'fliegen', 'sing', 'federn', 'käfig'] },
    { name: 'Aquariumfisch', category: 'pets', tags: ['tier', 'wasser', 'aquarium', 'schwimmen', 'haustier'] },
    { name: 'Hase', category: 'pets', tags: ['tier', 'langeohren', 'hoppeln', 'karotte', 'fell'] },
    { name: 'Hausmaus', category: 'pets', tags: ['tier', 'klein', 'nagetier', 'haustier', 'grau'] },
    { name: 'Hamster', category: 'pets', tags: ['tier', 'klein', 'rad', 'nagetier', 'käfig'] },
    { name: 'Pferd', category: 'pets', tags: ['tier', 'reiten', 'gross', 'stall', 'mähne'] },
    { name: 'Kuh', category: 'pets', tags: ['tier', 'milch', 'bauernhof', 'fleck', 'muh'] },
    { name: 'Schwein', category: 'pets', tags: ['tier', 'rosa', 'bauernhof', 'glück', 'borsten'] },
    { name: 'Huhn', category: 'pets', tags: ['tier', 'ei', 'bauernhof', 'vogel', 'federn'] },
    { name: 'Schaf', category: 'pets', tags: ['tier', 'wolle', 'weiss', 'bauernhof', 'mähen'] },
    { name: 'Ente', category: 'pets', tags: ['tier', 'wasser', 'vogel', 'quaken', 'teich'] },
    { name: 'Hundeknochen', category: 'pets', tags: ['hund', 'essen', 'kauen', 'spielzeug', 'weiss'] },
    { name: 'Futternapf', category: 'pets', tags: ['essen', 'trinken', 'schüssel', 'tier', 'boden'] },
    { name: 'Hundeleine', category: 'pets', tags: ['hund', 'gehen', 'spazieren', 'band', 'kontrolle'] },
    { name: 'Tierspielzeug', category: 'pets', tags: ['spielen', 'spass', 'ball', 'tier', 'beschäftigung'] },
    { name: 'Tierkäfig', category: 'pets', tags: ['zuhause', 'gitter', 'vogel', 'hamster', 'schutz'] },
    { name: 'Aquarium', category: 'pets', tags: ['wasser', 'fisch', 'glas', 'deko', 'tank'] },
    { name: 'Pfote', category: 'pets', tags: ['fuss', 'abdruck', 'tier', 'spur', 'gehen'] },

    // Transport (nur Fahrzeuge)
    { name: 'Auto', category: 'transport', tags: ['fahren', 'strasse', 'motor', 'rad', 'pkw'] },
    { name: 'Fahrrad', category: 'transport', tags: ['fahren', 'sport', 'zweirad', 'pedal', 'umwelt'] },
    { name: 'Bus', category: 'transport', tags: ['öpnv', 'gross', 'haltestelle', 'fahren', 'passagiere'] },
    { name: 'LKW', category: 'transport', tags: ['lastwagen', 'transport', 'gross', 'strasse', 'güter'] },
    { name: 'Motorrad', category: 'transport', tags: ['schnell', 'zweirad', 'helm', 'motor', 'laut'] },
    { name: 'Motorroller', category: 'transport', tags: ['stadt', 'zweirad', 'motor', 'klein', 'vespa'] },
    { name: 'Tretroller', category: 'transport', tags: ['kickscooter', 'zweirad', 'treten', 'kinder', 'spass'] },
    { name: 'E-Scooter', category: 'transport', tags: ['elektrisch', 'zweirad', 'stadt', 'modern', 'sharing'] },
    { name: 'Zug', category: 'transport', tags: ['schiene', 'bahnhof', 'schnell', 'reise', 'wagon'] },
    { name: 'Strassenbahn', category: 'transport', tags: ['stadt', 'schiene', 'öpnv', 'elektrisch', 'bahn'] },
    { name: 'U-Bahn', category: 'transport', tags: ['untergrund', 'tunnel', 'stadt', 'schnell', 'metro'] },
    { name: 'Flugzeug', category: 'transport', tags: ['fliegen', 'himmel', 'reise', 'schnell', 'airport'] },
    { name: 'Hubschrauber', category: 'transport', tags: ['helikopter', 'propeller', 'vertikal', 'luft', 'pilot'] },
    { name: 'Schiff', category: 'transport', tags: ['wasser', 'meer', 'gross', 'hafen', 'kapitän'] },
    { name: 'Boot', category: 'transport', tags: ['klein', 'wasser', 'paddel', 'see', 'angeln'] },
    { name: 'Rakete', category: 'transport', tags: ['weltraum', 'start', 'feuer', 'nasa', 'schnell'] },
    { name: 'Ampel', category: 'transport', tags: ['verkehr', 'rot', 'grün', 'stopp', 'licht'] },
    { name: 'Verkehrsschild', category: 'transport', tags: ['verkehr', 'hinweis', 'strasse', 'regel', 'achtung'] },
    { name: 'Strasse', category: 'transport', tags: ['asphalt', 'weg', 'auto', 'fahren', 'bahn'] },
    { name: 'Tankstelle', category: 'transport', tags: ['benzin', 'auto', 'energie', 'tanken', 'shop'] },
    { name: 'Parkplatz', category: 'transport', tags: ['auto', 'stehen', 'schild', 'p-zeichen', 'fläche'] },
    { name: 'Garage', category: 'transport', tags: ['haus', 'auto', 'parken', 'tor', 'schutz'] },
];
